### ISSUE TITLE
 Help guys “”face_img = cv2.resize(face_img, (width, height))“” webui issue.

### ISSUE THREAD

**Issue by Softysoftyball** [BadToBest/EchoMimic#102]
Traceback (most recent call last):
  File "/home/rong/anaconda3/envs/echomimic/lib/python3.8/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/home/rong/anaconda3/envs/echomimic/lib/python3.8/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/rong/anaconda3/envs/echomimic/lib/python3.8/site-packages/gradio/blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "/home/rong/anaconda3/envs/echomimic/lib/python3.8/site-packages/gradio/blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/home/rong/anaconda3/envs/echomimic/lib/python3.8/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/rong/anaconda3/envs/echomimic/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/home/rong/anaconda3/envs/echomimic/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/home/rong/anaconda3/envs/echomimic/lib/python3.8/site-packages/gradio/utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "webgui.py", line 255, in generate_video
    final_output_path = process_video(
  File "webgui.py", line 179, in process_video
    face_img = cv2.resize(face_img, (width, height))
TypeError: Expected Ptr<cv::UMat> for argument 'src'

**Comment by cdg1921** [comment]
same issue

**Comment by andchir** [comment]
Hello!
Need to replace:
```
face_img = crop_and_pad(face_img, crop_rect)
face_mask = crop_and_pad(face_mask, crop_rect)
```
to:
```
face_img, _ = crop_and_pad(face_img, crop_rect)
face_mask, _ = crop_and_pad(face_mask, crop_rect)
```

**Comment by pli2014** [comment]
[bug 128](https://github.com/BadToBest/EchoMimic/issues/128) has solved it.
