### ISSUE TITLE
执行python -u infer_audio2vid.py 报错:No module named 'cv2'

### ISSUE THREAD

**Issue by yeohx** [BadToBest/EchoMimic#108]
python -u webgui.py --server_port=3000
Traceback (most recent call last):
  File "/root/EchoMimic/webgui.py", line 12, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
(base) [root@iZrj9btw2sw63gaduxfvbgZ EchoMimic]# python -u infer_audio2vid.py
Traceback (most recent call last):
  File "/root/EchoMimic/infer_audio2vid.py", line 18, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

python 版本 3.10.0
centos7

**Comment by yiyijiu92** [comment]
same problem +1

**Comment by yeohx** [comment]
选择有显卡的服务器,依赖重新安装.注意安装显卡驱动. 注意版本
