### ISSUE TITLE
安装依赖报错

### ISSUE THREAD

**Issue by yeohx** [BadToBest/EchoMimic#134]
我的环境是:
Ubuntu 22.04 64位
python 3.10.12
conda:
https://repo.anaconda.com/miniconda/Miniconda3-py310_24.5.0-0-Linux-x86_64.sh
安装之后执行:python -u infer_audio2vid.py 
报错:
Traceback (most recent call last):
  File "/root/EchoMimic/infer_audio2vid.py", line 18, in <module>
    import cv2
  File "/root/miniconda3/envs/echomimic/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/root/miniconda3/envs/echomimic/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/root/miniconda3/envs/echomimic/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

安装过程如下:
wget https://repo.anaconda.com/miniconda/Miniconda3-py310_24.5.0-0-Linux-x86_64.sh
sh Miniconda3-py10_24.5.0-0-Linux-x86_64.sh
conda init

安装EchoMimic
1. git clone https://github.com/BadToBest/EchoMimic
2. cd EchoMimic
3. conda create -n echomimic python=3.10.2
4. conda activate echomimic
5. pip install -r requirements.txt

安装:ffmpeg-static
wget https://www.johnvansickle.com/ffmpeg/old-releases/ffmpeg-4.4-amd64-static.tar.xz
tar -xJf ffmpeg-4.4-amd64-static.tar.xz
cd ffmpeg-4.4-amd64-static
pwd
export FFMPEG_PATH=/path/to/ffmpeg-4.4-amd64-static
    
安装:pretrained weights 

sudo apt update
sudo apt install curl git
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
sudo apt install git-lfs
git lfs install
git lfs version

git clone https://huggingface.co/BadToBest/EchoMimic pretrained_weights

**Comment by ng-fukgin** [comment]
你这个是少了一些依赖库，试试
apt-get update
apt-get install libgl1-mesa-glx
