### ISSUE TITLE
Cannot process type as video: <class 'pathlib.WindowsPath'>

### ISSUE THREAD

**Issue by HandsomeDong** [BadToBest/EchoMimic#136]
It seems that the video was generated successfully, but an exception occurred when it was displayed to the webui.

```
Moviepy - video ready output\tmp\output_video_with_audio.mp4
Traceback (most recent call last):
  File "C:\Users\HandsomeDong\.conda\envs\echomimic\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\HandsomeDong\.conda\envs\echomimic\lib\site-packages\gradio\blocks.py", line 1349, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\HandsomeDong\.conda\envs\echomimic\lib\site-packages\gradio\blocks.py", line 1283, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\HandsomeDong\.conda\envs\echomimic\lib\site-packages\gradio\components.py", line 2202, in postprocess
    raise Exception(f"Cannot process type as video: {type(y)}")
Exception: Cannot process type as video: <class 'pathlib.WindowsPath'>
```

![image](https://github.com/user-attachments/assets/02f59760-fd9e-40e5-8bc2-f753de941360)
![image](https://github.com/user-attachments/assets/3f82dd59-9160-4fef-be0c-4a29fc7a35cb)
![image](https://github.com/user-attachments/assets/a293bc97-0341-4b80-b1ab-23cf46bf887e)

**Comment by HandsomeDong** [comment]
I changed the code of function process_video, but it did not work.

![image](https://github.com/user-attachments/assets/e4aa323f-f0f6-405e-baa1-434bb8c08602)
