### ISSUE TITLE
memory leakage

### ISSUE THREAD

**Issue by medalawi** [BadToBest/EchoMimic#143]
how to fix memory leakage while loading webgui.py
could someone please edit the code to work without cuda error

`Traceback (most recent call last):
  File "webgui.py", line 83, in <module>
    denoising_unet = EchoUNet3DConditionModel.from_pretrained_2d(
  File "/home/ubuntu/anaconda3/envs/echomimic/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1154, in to
    return self._apply(convert)
  File "/home/ubuntu/anaconda3/envs/echomimic/lib/python3.8/site-packages/torch/nn/modules/module.py", line 804, in _apply
    module._apply(fn)
  File "/home/ubuntu/anaconda3/envs/echomimic/lib/python3.8/site-packages/torch/nn/modules/module.py", line 804, in _apply
    module._apply(fn)
  File "/home/ubuntu/anaconda3/envs/echomimic/lib/python3.8/site-packages/torch/nn/modules/module.py", line 804, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/home/ubuntu/anaconda3/envs/echomimic/lib/python3.8/site-packages/torch/nn/modules/module.py", line 827, in _apply
    param_applied = fn(param)
  File "/home/ubuntu/anaconda3/envs/echomimic/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1152, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 0 has a total capacity of 3.95 GiB of which 3.75 MiB is free. Including non-PyTorch memory, this process has 3.94 GiB memory in use. Of the allocated memory 3.76 GiB is allocated by PyTorch, and 153.69 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory M`

**Comment by medalawi** [comment]
I found this [comfyui_echomimic](https://github.com/smthemex/ComfyUI_EchoMimic) will fix Vram issue by load it on CPU its slow but beter than VRAM ERROR
