### ISSUE TITLE
请问执行是怎么回事。这个问题出在哪里。

### ISSUE THREAD

**Issue by laochendeai** [BadToBest/EchoMimic#155]
To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "E:\EchoMimic\envmimic\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "E:\EchoMimic\envmimic\lib\site-packages\gradio\route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\EchoMimic\envmimic\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "E:\EchoMimic\envmimic\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "E:\EchoMimic\envmimic\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\EchoMimic\envmimic\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "E:\EchoMimic\envmimic\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "E:\EchoMimic\envmimic\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "E:\EchoMimic\webgui.py", line 247, in generate_video
    final_output_path = process_video(
  File "E:\EchoMimic\webgui.py", line 183, in process_video
    face_img = cv2.resize(face_img, (width, height))
cv2.error: OpenCV(4.10.0) :-1: error: (-5:Bad argument) in function 'resize'
> Overload resolution failed:
>  - src is not a numerical tuple
>  - Expected Ptr<cv::UMat> for argument 'src'

**Comment by laochendeai** [comment]
https://github.com/BadToBest/EchoMimic/issues/90#issuecomment-2254123419按这个解决了
