### ISSUE TITLE
Getting issue in 'src\models\unet_2d_blocks.py' DownEncoderBlock2D does not exist

### ISSUE THREAD

**Issue by RushabhShahPrograms** [BadToBest/EchoMimic#163]
I downloaded every pre-trained model available on the hugging space echomimic page. And get the zip of this github repo and added inside one folder. Please help me to resolve this issue

Thanks in advance

Now whenever I run the code I get this kind of error

**Error 1**
```
(echomimic) D:\MTECH\Brainy_Neurals\07-lipsync\19-Avatar\Echomimic>python webgui.py --server_port=3000
C:\Users\RUSHABH\.conda\envs\echomimic\lib\site-packages\diffusers\utils\outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
C:\Users\RUSHABH\.conda\envs\echomimic\lib\site-packages\diffusers\utils\outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
C:\Users\RUSHABH\.conda\envs\echomimic\lib\site-packages\diffusers\utils\outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
add ffmpeg to path
Traceback (most recent call last):
  File "D:\MTECH\Brainy_Neurals\07-lipsync\19-Avatar\Echomimic\webgui.py", line 73, in <module>
    reference_unet = UNet2DConditionModel.from_pretrained(
  File "C:\Users\RUSHABH\.conda\envs\echomimic\lib\site-packages\diffusers\models\modeling_utils.py", line 795, in from_pretrained
    model = cls.from_config(config, **unused_kwargs)
  File "C:\Users\RUSHABH\.conda\envs\echomimic\lib\site-packages\diffusers\configuration_utils.py", line 255, in from_config
    model = cls(**init_dict)
  File "C:\Users\RUSHABH\.conda\envs\echomimic\lib\site-packages\diffusers\configuration_utils.py", line 645, in inner_init
    init(self, *args, **init_kwargs)
  File "D:\MTECH\Brainy_Neurals\07-lipsync\19-Avatar\Echomimic\src\models\unet_2d_condition.py", line 499, in __init__
    down_block = get_down_block(
  File "D:\MTECH\Brainy_Neurals\07-lipsync\19-Avatar\Echomimic\src\models\unet_2d_blocks.py", line 99, in get_down_block
    raise ValueError(f"{down_block_type} does not exist.")
ValueError: DownEncoderBlock2D does not exist.
```

**Error 2**
```
Traceback (most recent call last):
  File "C:\Users\RUSHABH\.conda\envs\echomimic\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\RUSHABH\.conda\envs\echomimic\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\RUSHABH\.conda\envs\echomimic\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "C:\Users\RUSHABH\.conda\envs\echomimic\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\Users\RUSHABH\.conda\envs\echomimic\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\RUSHABH\.conda\envs\echomimic\lib\site-packages\anyio\_backends\_asyncio.py", line 2357, in run_sync_in_worker_thread
    return await future
  File "C:\Users\RUSHABH\.conda\envs\echomimic\lib\site-packages\anyio\_backends\_asyncio.py", line 864, in run
    result = context.run(func, *args)
  File "C:\Users\RUSHABH\.conda\envs\echomimic\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "webgui.py", line 233, in generate_video
    final_output_path = process_video(
  File "webgui.py", line 169, in process_video
    face_img = cv2.resize(face_img, (width, height))
cv2.error: OpenCV(4.10.0) :-1: error: (-5:Bad argument) in function 'resize'
> Overload resolution failed:
>  - src is not a numerical tuple
>  - Expected Ptr<cv::UMat> for argument 'src'
```

**Comment by RafaelGodoyEbert** [comment]
How to solve?

**Comment by RushabhShahPrograms** [comment]
> How to solve?

Actually while downloading pretrained_weights folders some weights and python scripts were not downloaded properly so it was giving me this error. I again downloaded whole pretrained_weights folder then I didn't received this error anymore
