### ISSUE TITLE
ffmpeg issue FileNotFoundError: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by congge27** [BadToBest/EchoMimic#186]
基础环境：
windows 11
4070
anaconda

按照官方教程配置换环境，下载了依赖包，下载了ffmpeg也配置了环境变量，但是一运行就显示这个问题，
现在在控制台直接运行 ffmpeg是可以的，不知道什么情况了，求教

```
Adding FFMPEG_PATH to PATH

Traceback (most recent call last):
  File "infer_audio2vid.py", line 258, in <module>
    main()
  File "infer_audio2vid.py", line 226, in main
    video = pipe(
  File "D:\software\anaconda\envs\EchoMimic\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\python-pro\EchoMimic\src\pipelines\pipeline_echo_mimic.py", line 395, in __call__
    whisper_feature = self.audio_guider.audio2feat(audio_path)
  File "D:\python-pro\EchoMimic\src\models\whisper\audio2feature.py", line 100, in audio2feat
    result = self.model.transcribe(audio_path)
  File "D:\python-pro\EchoMimic\src\models\whisper\whisper\transcribe.py", line 85, in transcribe
    mel = log_mel_spectrogram(audio)
  File "D:\python-pro\EchoMimic\src\models\whisper\whisper\audio.py", line 112, in log_mel_spectrogram
    audio = load_audio(audio)
  File "D:\python-pro\EchoMimic\src\models\whisper\whisper\audio.py", line 43, in load_audio
    ffmpeg.input(file, threads=0)
  File "D:\software\anaconda\envs\EchoMimic\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "D:\software\anaconda\envs\EchoMimic\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "D:\software\anaconda\envs\EchoMimic\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\software\anaconda\envs\EchoMimic\lib\subprocess.py", line 1327, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。


```

**Comment by AHannanSaal** [comment]
I had the same problem, it is related to ffmpeg or maybe you have installed the wrong version like I did. 

if you've installed both, ffmpeg and ffmpeg-python.
uninstall both with:
pip uninstall ffmpeg
pip uninstall ffmpeg-python

and install ffmpeg-python again with :
pip install ffmpeg-python

**Comment by Surrin1999** [comment]
同样问题已解决，下载https://github.com/GyanD/codexffmpeg/releases/download/5.0/ffmpeg-5.0-full_build.7z，解压后配置环境变量即可，官方给的那个是Linux下的ffmpeg静态库
