### ISSUE TITLE
做了个 gradio demo 和 jupyter notebook

### ISSUE THREAD

**Issue by O-O1024** [BadToBest/EchoMimic#22]
解压文件放到 EchoMimic 根目录下
[gradio demo and jupyter notebook.zip](https://github.com/user-attachments/files/16177548/gradio.demo.and.jupyter.notebook.zip)

**Comment by jkla139** [comment]
![Gradio](https://github.com/BadToBest/EchoMimic/assets/44624598/155b9608-6e2b-4828-8573-bb1f87dfcc6c)

![搜狗截图20240711211409](https://github.com/BadToBest/EchoMimic/assets/44624598/d530856f-0ff4-44e5-ba67-6b7a1b71b8f1)

**Comment by nitinmukesh** [comment]
What dependencies to be installed for gradio?
Anything else required other than pip install gradio

**Comment by O-O1024** [comment]
> @O-O1024 gradio 需要安装哪些依赖项？ 除了 pip install gradio 之外，还需要其他什么

original requirements + gradio, IPython ...
You can try to run these files and see the errors

**Comment by yuange250** [comment]
厉害了我的哥👍👍👍

**Comment by nitinmukesh** [comment]
@O-O1024 @stella0909  @yuange250 

Please if anyone can share pip list

I am getting this error

```
(echomimic) C:\sd\EchoMimic>python gradio_app.py
Traceback (most recent call last):
  File "gradio_app.py", line 5, in <module>
    from my_infer_audio2vid import load_config, load_models, infer
  File "C:\sd\EchoMimic\my_infer_audio2vid.py", line 23, in <module>
    from src.models.unet_2d_condition import UNet2DConditionModel
  File "C:\sd\EchoMimic\src\models\unet_2d_condition.py", line 10, in <module>
    from diffusers.models.activations import get_activation
ModuleNotFoundError: No module named 'diffusers.models.activations'

```
I have diffusers and gradio installed

```
(echomimic) C:\sd\EchoMimic>pip list
Package                   Version
------------------------- ------------
absl-py                   2.1.0
accelerate                0.32.1
aiofiles                  23.2.1
aiohttp                   3.9.5
aiosignal                 1.3.1
albumentations            1.1.0
altair                    5.3.0
annotated-types           0.7.0
antlr4-python3-runtime    4.8
anyio                     4.4.0
asgiref                   3.8.1
asttokens                 2.4.1
async-timeout             4.0.3
attrs                     23.2.0
av                        11.0.0
backcall                  0.2.0
backports.zoneinfo        0.2.1
blinker                   1.8.2
blosc2                    2.0.0
boto3                     1.34.143
botocore                  1.34.143
cachetools                5.3.3
certifi                   2024.7.4
charset-normalizer        3.3.2
clean-fid                 0.1.35
click                     8.1.7
colorama                  0.4.6
colorlog                  6.8.2
configobj                 5.0.8
contourpy                 1.1.1
cycler                    0.12.1
Cython                    3.0.10
datasets                  2.20.0
decorator                 5.1.1
decord                    0.6.0
deepdish                  0.3.7
Deprecated                1.2.14
diffusers                 0.14.0
dill                      0.3.8
Django                    4.2.14
dnspython                 2.6.1
docker-pycreds            0.4.0
easydict                  1.13
einops                    0.4.1
email_validator           2.2.0
ete3                      3.1.3
exceptiongroup            1.2.1
executing                 2.0.1
facenet-pytorch           2.5.0
fastapi                   0.111.0
fastapi-cli               0.0.4
ffmpeg-python             0.2.0
ffmpy                     0.3.2
filelock                  3.15.4
fonttools                 4.53.1
frozenlist                1.4.1
fsspec                    2024.5.0
ftfy                      6.0.3
future                    1.0.0
gitdb                     4.0.11
GitPython                 3.1.43
google-auth               2.32.0
google-auth-oauthlib      1.0.0
gradio                    4.37.2
gradio_client             1.0.2
grpcio                    1.64.1
h11                       0.14.0
h5py                      3.11.0
httpcore                  1.0.5
httptools                 0.6.1
httpx                     0.27.0
huggingface-hub           0.23.4
idna                      3.7
imageio                   2.14.1
imageio-ffmpeg            0.4.7
importlib_metadata        8.0.0
importlib_resources       6.4.0
intel-openmp              2021.4.0
invisible-watermark       0.2.0
ipdb                      0.13.13
ipython                   8.12.3
jedi                      0.19.1
Jinja2                    3.1.4
jmespath                  1.0.1
joblib                    1.4.2
json-lines                0.5.0
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
kornia                    0.6.0
lazy_loader               0.4
lightning-utilities       0.11.3.post0
lpips                     0.1.4
Markdown                  3.6
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.7.5
matplotlib-inline         0.1.7
mdurl                     0.1.2
mkl                       2021.4.0
moviepy                   1.0.3
mpmath                    1.3.0
msgpack                   1.0.8
multidict                 6.0.5
multiprocess              0.70.16
networkx                  3.1
nltk                      3.8.1
numexpr                   2.8.6
numpy                     1.24.4
oauthlib                  3.2.2
omegaconf                 2.1.1
opencv-python             4.2.0.34
opencv-python-headless    4.10.0.84
orderedset                2.0.3
orjson                    3.10.6
packaging                 24.1
pandas                    2.0.3
parso                     0.8.4
pickleshare               0.7.5
Pillow                    9.0.1
pip                       24.0
pkgutil_resolve_name      1.3.10
platformdirs              4.2.2
proglog                   0.1.10
progressbar               2.5
prompt_toolkit            3.0.47
protobuf                  5.27.2
psutil                    6.0.0
pudb                      2019.2
pure-eval                 0.2.2
py-cpuinfo                9.0.0
pyarrow                   16.1.0
pyarrow-hotfix            0.6
pyasn1                    0.6.0
pyasn1_modules            0.4.0
pydantic                  2.8.2
pydantic_core             2.20.1
pydeck                    0.9.1
pyDeprecate               0.3.1
pydub                     0.25.1
Pygments                  2.18.0
pymongo                   4.8.0
pyparsing                 3.1.2
python-dateutil           2.9.0.post0
python-dotenv             1.0.1
python-magic              0.4.27
python-multipart          0.0.9
pytorch-fid               0.3.0
pytorch-lightning         1.5.9
pytz                      2024.1
PyWavelets                1.4.1
PyYAML                    6.0.1
qudida                    0.0.4
referencing               0.35.1
regex                     2024.5.15
requests                  2.32.3
requests-oauthlib         2.0.0
rich                      13.7.1
rouge_score               0.1.2
rpds-py                   0.19.0
rsa                       4.9
ruff                      0.5.1
s3transfer                0.10.2
safetensors               0.4.3
scikit-image              0.20.0
scikit-learn              1.3.2
scipy                     1.9.1
semantic-version          2.10.0
sentry-sdk                2.9.0
setproctitle              1.3.3
setuptools                59.5.0
shellingham               1.5.4
simplejson                3.19.2
six                       1.16.0
smmap                     5.0.1
sniffio                   1.3.1
sqlparse                  0.5.0
stack-data                0.6.3
starlette                 0.37.2
streamlit                 1.36.0
sympy                     1.13.0
tables                    3.8.0
tbb                       2021.13.0
tenacity                  8.5.0
tensorboard               2.14.0
tensorboard-data-server   0.7.2
tensorboardX              2.4.1
test_tube                 0.7.5
threadpoolctl             3.5.0
tifffile                  2023.7.10
timm                      1.0.7
tokenizers                0.13.3
toml                      0.10.2
tomli                     2.0.1
tomlkit                   0.12.0
toolz                     0.12.1
torch                     1.12.1+cu113
torch-fidelity            0.3.0
torchaudio                2.3.1
torchmetrics              0.6.0
torchtyping               0.1.4
torchvision               0.13.1+cu113
tornado                   6.4.1
tqdm                      4.66.4
traitlets                 5.14.3
transformers              4.27.4
typeguard                 4.3.0
typer                     0.12.3
typing_extensions         4.12.2
tzdata                    2024.1
ujson                     5.10.0
urllib3                   2.2.2
urwid                     2.6.15
uvicorn                   0.30.1
wandb                     0.17.4
watchdog                  4.0.1
watchfiles                0.22.0
wcwidth                   0.2.13
websockets                11.0.3
Werkzeug                  3.0.3
wheel                     0.43.0
wrapt                     1.16.0
xxhash                    3.4.1
yacs                      0.1.8
yarl                      1.9.4
zipp                      3.19.2
```
