### ISSUE TITLE
NameError: name 'zero_locator_tensor' is not defined

### ISSUE THREAD

**Issue by kev123456** [BadToBest/EchoMimic#61]
Error occered when runing `python -u infer_audio2vid_pose.py`

Traceback (most recent call last):
  File "infer_audio2vid_pose.py", line 231, in <module>
    main()
  File "infer_audio2vid_pose.py", line 197, in main
    video = pipe(
  File "/mnt/data/kev/miniconda3/envs/echomimic/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/data/kev/project/EchoMimic/src/pipelines/pipeline_echo_mimic_pose.py", line 543, in __call__
    zero_pose_latents = torch.cat([zero_locator_tensor[:, :, c] for c in new_context]).to(device)
  File "/mnt/data/kev/project/EchoMimic/src/pipelines/pipeline_echo_mimic_pose.py", line 543, in <listcomp>
    zero_pose_latents = torch.cat([zero_locator_tensor[:, :, c] for c in new_context]).to(device)
NameError: name 'zero_locator_tensor' is not defined

**Comment by ArvinC** [comment]
遇到了同样的问题

**Comment by oisilener1982** [comment]
Just follow the tutorial here and you should be fine. https://www.youtube.com/watch?v=WtHdvSSQlWo

Dont follow the official guide. I got lots and lots of error until i got tired. Luckily i found the video above

**Comment by zhangdanfeng888** [comment]
+1，请问这个问题解决了吗？感觉像是少了段代码

**Comment by why-26** [comment]
Hello, after analyzing the project code, I conducted a successful attempt. I added the following line in the pipeline_echo_mimic_pose.py file: zero_locator_tensor = torch.zeros_like(face_locator_tensor). Here is the position where it was added, as shown in the figure. Then, I was able to successfully run the infer_audio2vid_pose.py file and obtained the inference result video. I hope this method works for everyone.
<img width="828" alt="github_echomimic_q1" src="https://github.com/user-attachments/assets/a90c6ef7-72ae-42b4-b97c-2e77272ad8f7">

**Comment by municef1** [comment]
> Hello, after analyzing the project code, I conducted a successful attempt. I added the following line in the pipeline_echo_mimic_pose.py file: zero_locator_tensor = torch.zeros_like(face_locator_tensor). Here is the position where it was added, as shown in the figure. Then, I was able to successfully run the infer_audio2vid_pose.py file and obtained the inference result video. I hope this method works for everyone. <img alt="github_echomimic_q1" width="828" src="https://private-user-images.githubusercontent.com/58427077/351330721-a90c6ef7-72ae-42b4-b97c-2e77272ad8f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4Njc2NjksIm5iZiI6MTcyMTg2NzM2OSwicGF0aCI6Ii81ODQyNzA3Ny8zNTEzMzA3MjEtYTkwYzZlZjctNzJhZS00MmI0LWI5N2MtMmU3NzI3MmFkOGY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDAwMjkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlNzY0MGExYzY5YjNjZTc1NWRhOTViY2JiNWIwZDRhNDFlZTUxNDgxYmU4OWE4OWNlNThlYjdhZTczMmU2ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vklqLvv5R4DEqLXOFQIAU8J4IaJvy7wa0c3NPWfkQRc">

Thanks for your tips!

In pipeline_echo_mimic_pose.py, I removed zero_pose latents, and edited `pose_latents`,
`pose_latents = torch.cat([torch.zeros_like(pose_latents_cond), pose_latents_cond], 0)`

so I didn't have to make `zero_locator_tensor` and `zero_pose_latents`

**Comment by JoeFannie** [comment]
It is a bug. We have fixed it in the latest version.
