### ISSUE TITLE
请问pytorch版本什么要求，安装后报错

### ISSUE THREAD

**Issue by seekme-ai** [BadToBest/EchoMimic#68]
(echomimic) PS E:\code\Live_Portrait\EchoMimic> python -c "import torch; print(torch.__version__)"
2.2.2+cpu
(echomimic) PS E:\code\Live_Portrait\EchoMimic> 
(echomimic) PS E:\code\Live_Portrait\EchoMimic>
(echomimic) PS E:\code\Live_Portrait\EchoMimic>
(echomimic) PS E:\code\Live_Portrait\EchoMimic>
(echomimic) PS E:\code\Live_Portrait\EchoMimic>
(echomimic) PS E:\code\Live_Portrait\EchoMimic>   python -u infer_audio2vid.py                                                             
C:\Users\seekm\anaconda3\envs\echomimic\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
C:\Users\seekm\anaconda3\envs\echomimic\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
C:\Users\seekm\anaconda3\envs\echomimic\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with:
```
pip install accelerate
```
.
Traceback (most recent call last):
  File "infer_audio2vid.py", line 257, in <module>
    main()
  File "infer_audio2vid.py", line 111, in main
    vae = AutoencoderKL.from_pretrained(
  File "C:\Users\seekm\anaconda3\envs\echomimic\lib\site-packages\torch\nn\modules\module.py", line 1152, in to
    return self._apply(convert)
  File "C:\Users\seekm\anaconda3\envs\echomimic\lib\site-packages\torch\nn\modules\module.py", line 802, in _apply
    module._apply(fn)
  File "C:\Users\seekm\anaconda3\envs\echomimic\lib\site-packages\torch\nn\modules\module.py", line 802, in _apply
    module._apply(fn)
  File "C:\Users\seekm\anaconda3\envs\echomimic\lib\site-packages\torch\nn\modules\module.py", line 825, in _apply
    param_applied = fn(param)
  File "C:\Users\seekm\anaconda3\envs\echomimic\lib\site-packages\torch\nn\modules\module.py", line 1150, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "C:\Users\seekm\anaconda3\envs\echomimic\lib\site-packages\torch\cuda\__init__.py", line 293, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by yuange250** [comment]
这个貌似跟版本没关系，跟安装torch时的cuda环境变量关系可能更大

**Comment by seekme-ai** [comment]
请问有修改建议么，cuda是之前安装好的12.4版本，环境变量没有做额外配置

**Comment by seekme-ai** [comment]
cuda没安装好导致的，已解决
