### ISSUE TITLE
执行demo脚本报错RuntimeError: Failed to import transformers.models.clip.image_processing_clip

### ISSUE THREAD

**Issue by seekme-ai** [BadToBest/EchoMimic#73]
(echomimic) PS E:\code\Live_Portrait\EchoMimic> python -u infer_audio2vid.py     
C:\Users\seekm\anaconda3\envs\echomimic\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
C:\Users\seekm\anaconda3\envs\echomimic\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Traceback (most recent call last):
  File "C:\Users\seekm\anaconda3\envs\echomimic\lib\site-packages\transformers\utils\import_utils.py", line 1567, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\seekm\anaconda3\envs\echomimic\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\seekm\anaconda3\envs\echomimic\lib\site-packages\transformers\models\clip\image_processing_clip.py", line 21, in <module>
    from ...image_processing_utils import BaseImageProcessor, BatchFeature, get_size_dict
  File "C:\Users\seekm\anaconda3\envs\echomimic\lib\site-packages\transformers\image_processing_utils.py", line 21, in <module>
    from .image_transforms import center_crop, normalize, rescale
  File "C:\Users\seekm\anaconda3\envs\echomimic\lib\site-packages\transformers\image_transforms.py", line 22, in <module>
    from .image_utils import (
  File "C:\Users\seekm\anaconda3\envs\echomimic\lib\site-packages\transformers\image_utils.py", line 58, in <module>
    from torchvision.transforms import InterpolationMode
  File "C:\Users\seekm\anaconda3\envs\echomimic\lib\site-packages\torchvision\__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "C:\Users\seekm\anaconda3\envs\echomimic\lib\site-packages\torchvision\datasets\__init__.py", line 1, in <module>
    from ._optical_flow import FlyingChairs, FlyingThings3D, HD1K, KittiFlow, Sintel
  File "C:\Users\seekm\anaconda3\envs\echomimic\lib\site-packages\torchvision\datasets\_optical_flow.py", line 12, in <module>
    from ..io.image import _read_png_16
  File "C:\Users\seekm\anaconda3\envs\echomimic\lib\site-packages\torchvision\io\__init__.py", line 36, in <module>
    from .video import read_video, read_video_timestamps, write_video
  File "C:\Users\seekm\anaconda3\envs\echomimic\lib\site-packages\torchvision\io\video.py", line 16, in <module>
    import av
  File "C:\Users\seekm\anaconda3\envs\echomimic\lib\site-packages\av\__init__.py", line 23, in <module>
    _delvewheel_patch_1_5_1()
  File "C:\Users\seekm\anaconda3\envs\echomimic\lib\site-packages\av\__init__.py", line 20, in _delvewheel_patch_1_5_1
    raise OSError('Error loading {}; {}'.format(lib, ctypes.FormatError()))
OSError: Error loading libogg-0-f34e1352e804ae274f494f49de171881.dll; 操作成功完成。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "infer_audio2vid.py", line 28, in <module>
    from src.pipelines.pipeline_echo_mimic import Audio2VideoPipeline
  File "E:\code\Live_Portrait\EchoMimic\src\pipelines\pipeline_echo_mimic.py", line 32, in <module>
    from transformers import CLIPImageProcessor
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "C:\Users\seekm\anaconda3\envs\echomimic\lib\site-packages\transformers\utils\import_utils.py", line 1558, in __getattr__
    value = getattr(module, name)
  File "C:\Users\seekm\anaconda3\envs\echomimic\lib\site-packages\transformers\utils\import_utils.py", line 1557, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\seekm\anaconda3\envs\echomimic\lib\site-packages\transformers\utils\import_utils.py", line 1569, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.clip.image_processing_clip because of the following error (look up to see its traceback):
Error loading libogg-0-f34e1352e804ae274f494f49de171881.dll; 操作成功完成。

**Comment by JoeFannie** [comment]
检查下库是不是成功安装了
