### ISSUE TITLE
Error when generating video.

### ISSUE THREAD

**Issue by YTadF** [BadToBest/EchoMimic#76]
I'm trying to run this locally. I can get gradio to launch but whenever I try to generate a video, I get this error.

```
Traceback (most recent call last):
  File "C:\Users\Name\anaconda3\envs\echomimic\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\Name\anaconda3\envs\echomimic\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\Name\anaconda3\envs\echomimic\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "C:\Users\Name\anaconda3\envs\echomimic\lib\site-packages\gradio\blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\Users\Name\anaconda3\envs\echomimic\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\Name\anaconda3\envs\echomimic\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Name\anaconda3\envs\echomimic\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\Users\Name\anaconda3\envs\echomimic\lib\site-packages\gradio\utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "webgui.py", line 233, in generate_video
    final_output_path = process_video(
  File "webgui.py", line 175, in process_video
    video = pipe(
  File "C:\Users\Name\anaconda3\envs\echomimic\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Name\Desktop\work\AI\EchoMimic\src\pipelines\pipeline_echo_mimic.py", line 395, in __call__
    whisper_feature = self.audio_guider.audio2feat(audio_path)
  File "C:\Users\Name\Desktop\work\AI\EchoMimic\src\models\whisper\audio2feature.py", line 100, in audio2feat
    result = self.model.transcribe(audio_path)
  File "C:\Users\Name\Desktop\work\AI\EchoMimic\src\models\whisper\whisper\transcribe.py", line 85, in transcribe
    mel = log_mel_spectrogram(audio)
  File "C:\Users\Name\Desktop\work\AI\EchoMimic\src\models\whisper\whisper\audio.py", line 111, in log_mel_spectrogram
    audio = load_audio(audio)
  File "C:\Users\Name\Desktop\work\AI\EchoMimic\src\models\whisper\whisper\audio.py", line 42, in load_audio
    ffmpeg.input(file, threads=0)
  File "C:\Users\Name\anaconda3\envs\echomimic\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "C:\Users\Name\anaconda3\envs\echomimic\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "C:\Users\Name\anaconda3\envs\echomimic\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Name\anaconda3\envs\echomimic\lib\subprocess.py", line 1327, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by oisilener1982** [comment]
Just follow the tutorial here https://www.youtube.com/watch?v=WtHdvSSQlWo

**Comment by YTadF** [comment]
> Just follow the tutorial here https://www.youtube.com/watch?v=WtHdvSSQlWo
> 
> If you have problem due to the latest update the solution might be here #90

I had followed that video and got this error.
