### ISSUE TITLE
启动webgui.py，上传图片和音频后报错

### ISSUE THREAD

**Issue by hjj-lmx** [BadToBest/EchoMimic#90]
Traceback (most recent call last):
  File "D:\Program Files\miniconda3\envs\echomimic\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "D:\Program Files\miniconda3\envs\echomimic\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\Program Files\miniconda3\envs\echomimic\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "D:\Program Files\miniconda3\envs\echomimic\lib\site-packages\gradio\blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "D:\Program Files\miniconda3\envs\echomimic\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\Program Files\miniconda3\envs\echomimic\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "D:\Program Files\miniconda3\envs\echomimic\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "D:\Program Files\miniconda3\envs\echomimic\lib\site-packages\gradio\utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "webgui.py", line 233, in generate_video
    final_output_path = process_video(
  File "webgui.py", line 169, in process_video
    face_img = cv2.resize(face_img, (width, height))
cv2.error: OpenCV(4.10.0) :-1: error: (-5:Bad argument) in function 'resize'
> Overload resolution failed:
>  - src is not a numerical tuple
>  - Expected Ptr<cv::UMat> for argument 'src'

**Comment by JimmyMa99** [comment]
相同问题，等回复

**Comment by do-one-thing-to-well** [comment]
+1报错，不知道是不是python版本的问题，我是3.10，，看README，建议使用3.8是吧。

**Comment by oisilener1982** [comment]
same problem

**Comment by oisilener1982** [comment]
> +1 Error,I don't know if it's a python version problem.,I'm 3.10,,Look at README,It's recommended to use 3.8..,It's right.。

This was tested in 3.10

Python Environment Setup
Tested System Environment: Centos 7.2/Ubuntu 22.04, Cuda >= 11.7
Tested GPUs: A100(80G) / RTX4090D (24G) / V100(16G)
Tested Python Version: 3.8 / 3.10 / 3.11

**Comment by beierjie39** [comment]
同样问题+1

**Comment by oisilener1982** [comment]
We need @greengerong @Robin021 and @O-O1024. Please help us have a working gradio for echomimic

**Comment by CCmahua** [comment]
process_video函数下的
```
face_img = crop_and_pad(face_img, crop_rect)
face_mask = crop_and_pad(face_mask, crop_rect)
``` 
改为

```
face_img,crop_rect = crop_and_pad(face_img, crop_rect)
face_mask,crop_rect = crop_and_pad(face_mask, crop_rect)
```

**Comment by oisilener1982** [comment]
Thanks its working. Is there a way to make the webgui.py to use the accelerated infer_audio2vid_acc.py

**Comment by nitinmukesh** [comment]
@oisilener1982 @do-one-thing-to-well @beierjie39 

Attached file working for me

<img width="1232" alt="image" src="https://github.com/user-attachments/assets/fe4bd2cc-1b4b-43cb-9af9-be2f810092d3">


Command
python -u webgui_a2v_acc.py --server_port=3000

Download and extract in the installation folder
[webgui_a2v_acc.zip](https://github.com/user-attachments/files/16401040/webgui_a2v_acc.zip)

**Comment by oisilener1982** [comment]
![Capture](https://github.com/user-attachments/assets/17719c8c-3304-49d2-8b33-6791d383a4f0)
cv2.error: OpenCV(4.10.0) :-1: error: (-5:Bad argument) in function 'resize'
> Overload resolution failed:
>  - src is not a numerical tuple
>  - Expected Ptr<cv::UMat> for argument 'src'

**Comment by oisilener1982** [comment]
The uploaded file gives error. I dont understand how you got 6 steps if the steps in webgui_a2v_acc is 30

**Comment by CCmahua** [comment]
[webgui.zip](https://github.com/user-attachments/files/16402010/webgui.zip)
尝试下我这个版本，我已经使用了acc模型和解决error: (-5:Bad argument) in function 'resize'问题。

修改细节如下：

关于步骤为6和30的问题，请修改default_values中的steps。

然后
```
face_img,crop_rect = crop_and_pad(face_img, crop_rect)
face_mask,crop_rect = crop_and_pad(face_mask, crop_rect)
``` 
修改为
```
face_img,_ = crop_and_pad(face_img, crop_rect)
face_mask,_ = crop_and_pad(face_mask, crop_rect)
``` 

---

```
from src.pipelines.pipeline_echo_mimic import Audio2VideoPipeline
``` 
修改为

```
from src.pipelines.pipeline_echo_mimic_acc import Audio2VideoPipeline
``` 
---

```
config_path = "./configs/prompts/animation.yaml"
``` 

修改为

```
config_path = "./configs/prompts/animation_acc.yaml"
``` 
---

**Comment by oisilener1982** [comment]
can anyone confirm that the accelerated version has lower quality? Even if i try to increase the number of steps from 6 to 30 it is still have lower quality than the original/older version of echomimic

**Comment by xiaofanku** [comment]
cuda版本有要求吗?目前12.1报错了: `Torch not compiled with CUDA enabled`

**Comment by panmyuan** [comment]
![image](https://github.com/user-attachments/assets/67c83f35-c225-4c45-8753-096e39ff5df8)
![image](https://github.com/user-attachments/assets/eb15c8a0-96a2-4648-a06e-8becb16b2f4b)
有人碰到这个问题不

**Comment by ciscogeek** [comment]
Same issue. 
watch this.

**Comment by 13140438775** [comment]
> 修改细节如下：
> 
> 关于步骤为6和30的问题，请修改default_values中的steps。
> 
> 然后
> 
> ```
> face_img,crop_rect = crop_and_pad(face_img, crop_rect)
> ```

这个方案是可以的。

**Comment by ycruby** [comment]
![image](https://github.com/user-attachments/assets/2ba9f3ef-2bad-484f-a8f8-ec664a163fca)
有大佬遇到过这个问题吗，

**Comment by feria-tu** [comment]
> ![image](https://private-user-images.githubusercontent.com/129243509/378162866-2ba9f3ef-2bad-484f-a8f8-ec664a163fca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyODU0NDMsIm5iZiI6MTczMjI4NTE0MywicGF0aCI6Ii8xMjkyNDM1MDkvMzc4MTYyODY2LTJiYTlmM2VmLTJiYWQtNDg0Zi1hOGY4LWVjNjY0YTE2M2ZjYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQxNDE5MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OGQyMTI4NWMyNTBkYmYxMGU1ZDlhNTBkOTU2ODcyNmVhMjlhOGIzNGQ5OWJiOGE5ZTAzN2JkNTIwYmRlNzkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qJj0z8AseMUiuJ2oskEbqRXF4jObwY7fgkg9GHES870) 有大佬遇到过这个问题吗，

版本回退就行，这个很容易搜到
